<!doctype html>
<html>
<head>
    <title>index template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
</head>
<body>
    <div style="margin:0 auto;" >
        <div class="container" >
                <h1>Cadastros Localidades</h1>      
            <a href="/uf/cadastro"><button type="button" class="btn btn-info btn-lg">Cadastro de UF</button></a>
            <a href="/cidade/cadastro"><button type="button" class="btn btn-info btn-lg">Cadastro de cidades</button>
            
        </div>

        <div class="container" style="margin-top:30px;">
            <h2>Framework Express-tl</h2>
            
        </div>
    </div>
    
</body>
</html>